#!/bin/bash
mkdir bootstrap.d
cd bootstrap.d

if [ ! -e "external" ]; then
    ln -s ../external external
fi
if [ ! -e "src" ]; then
    ln -s ../src src
fi
mkdir -p obj/src/busy
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c src/busy/busy.cpp -o obj/src/busy/busy.o  -I src/busy -I src  -isystem src -isystem src -isystem src -isystem external/CommonOptions/external/SelfTest/external/Process/src -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/src/busy
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c src/busy/Project.cpp -o obj/src/busy/Project.o  -I src/busy -I src  -isystem src -isystem src -isystem src -isystem external/CommonOptions/external/SelfTest/external/Process/src -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/src/busy
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c src/busy/cache.cpp -o obj/src/busy/cache.o  -I src/busy -I src  -isystem src -isystem src -isystem src -isystem external/CommonOptions/external/SelfTest/external/Process/src -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/src/busy
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c src/busy/File.cpp -o obj/src/busy/File.o  -I src/busy -I src  -isystem src -isystem src -isystem src -isystem external/CommonOptions/external/SelfTest/external/Process/src -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/src/busy
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c src/busy/toolchains.cpp -o obj/src/busy/toolchains.o  -I src/busy -I src  -isystem src -isystem src -isystem src -isystem external/CommonOptions/external/SelfTest/external/Process/src -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/src/busy
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c src/busy/FileCache.cpp -o obj/src/busy/FileCache.o  -I src/busy -I src  -isystem src -isystem src -isystem src -isystem external/CommonOptions/external/SelfTest/external/Process/src -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/src/busy/utils
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c src/busy/utils/utils.cpp -o obj/src/busy/utils/utils.o  -I src/busy -I src  -isystem src -isystem src -isystem src -isystem external/CommonOptions/external/SelfTest/external/Process/src -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/src/busy
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c src/busy/Package.cpp -o obj/src/busy/Package.o  -I src/busy -I src  -isystem src -isystem src -isystem src -isystem external/CommonOptions/external/SelfTest/external/Process/src -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/src/busy
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c src/busy/CompilePipe.cpp -o obj/src/busy/CompilePipe.o  -I src/busy -I src  -isystem src -isystem src -isystem src -isystem external/CommonOptions/external/SelfTest/external/Process/src -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/src/base64
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c src/base64/base64.cpp -o obj/src/base64/base64.o  -I src/base64 -I src
mkdir -p obj/src/testBase64
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c src/testBase64/main.cpp -o obj/src/testBase64/main.o  -I src/testBase64 -I src  -isystem src
mkdir -p obj/external/ThreadPool/src/testThreadPool
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/ThreadPool/src/testThreadPool/testThreadPool.cpp -o obj/external/ThreadPool/src/testThreadPool/testThreadPool.o  -I external/ThreadPool/src/testThreadPool -I external/ThreadPool/src  -isystem external/ThreadPool/src -isystem external/ThreadPool/external/gtest/src -isystem external/ThreadPool/external/gtest/include -isystem external/CommonOptions/external/Serializer/external/gtest/src -isystem external/CommonOptions/external/Serializer/external/gtest/include
mkdir -p obj/external/ThreadPool/external/gtest/src/gtest/src
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/ThreadPool/external/gtest/src/gtest/src/gtest_main.cpp -o obj/external/ThreadPool/external/gtest/src/gtest/src/gtest_main.o  -I external/ThreadPool/external/gtest/src/gtest -I external/ThreadPool/external/gtest/include -I external/ThreadPool/external/gtest
mkdir -p obj/external/ThreadPool/external/gtest/src/gtest/src
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/ThreadPool/external/gtest/src/gtest/src/gtest-all.cpp -o obj/external/ThreadPool/external/gtest/src/gtest/src/gtest-all.o  -I external/ThreadPool/external/gtest/src/gtest -I external/ThreadPool/external/gtest/include -I external/ThreadPool/external/gtest
mkdir -p obj/external/CommonOptions/external/SelfTest/src/selfTest
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/SelfTest/src/selfTest/selfTest.cpp -o obj/external/CommonOptions/external/SelfTest/src/selfTest/selfTest.o  -I external/CommonOptions/external/SelfTest/src/selfTest -I external/CommonOptions/external/SelfTest/src  -isystem external/CommonOptions/external/SelfTest/external/Process/src
mkdir -p obj/external/CommonOptions/external/SelfTest/src/testSelfTest
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/SelfTest/src/testSelfTest/test.cpp -o obj/external/CommonOptions/external/SelfTest/src/testSelfTest/test.o  -I external/CommonOptions/external/SelfTest/src/testSelfTest -I external/CommonOptions/external/SelfTest/src  -isystem external/CommonOptions/external/SelfTest/src -isystem external/CommonOptions/external/SelfTest/external/Process/src
mkdir -p obj/external/CommonOptions/external/SelfTest/external/Process/src/process
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/SelfTest/external/Process/src/process/InteractiveProcess.cpp -o obj/external/CommonOptions/external/SelfTest/external/Process/src/process/InteractiveProcess.o  -I external/CommonOptions/external/SelfTest/external/Process/src/process -I external/CommonOptions/external/SelfTest/external/Process/src
mkdir -p obj/external/CommonOptions/external/SelfTest/external/Process/src/process
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/SelfTest/external/Process/src/process/Process.cpp -o obj/external/CommonOptions/external/SelfTest/external/Process/src/process/Process.o  -I external/CommonOptions/external/SelfTest/external/Process/src/process -I external/CommonOptions/external/SelfTest/external/Process/src
mkdir -p obj/external/CommonOptions/external/SelfTest/external/Process/src/testProcess
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/SelfTest/external/Process/src/testProcess/test.cpp -o obj/external/CommonOptions/external/SelfTest/external/Process/src/testProcess/test.o  -I external/CommonOptions/external/SelfTest/external/Process/src/testProcess -I external/CommonOptions/external/SelfTest/external/Process/src  -isystem external/CommonOptions/external/SelfTest/external/Process/src
mkdir -p obj/external/CommonOptions/external/Serializer/src/exampleSerializer
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/src/exampleSerializer/testFundamentals.cpp -o obj/external/CommonOptions/external/Serializer/src/exampleSerializer/testFundamentals.o  -I external/CommonOptions/external/Serializer/src/exampleSerializer -I external/CommonOptions/external/Serializer/src  -isystem external/CommonOptions/external/Serializer/src -isystem external/CommonOptions/external/Serializer/external/jsoncpp/src -isystem external/CommonOptions/external/Serializer/external/jsoncpp/include -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/src/exampleSerializerBinary
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/src/exampleSerializerBinary/testFundamentals.cpp -o obj/external/CommonOptions/external/Serializer/src/exampleSerializerBinary/testFundamentals.o  -I external/CommonOptions/external/Serializer/src/exampleSerializerBinary -I external/CommonOptions/external/Serializer/src  -isystem external/CommonOptions/external/Serializer/src -isystem external/CommonOptions/external/Serializer/external/jsoncpp/src -isystem external/CommonOptions/external/Serializer/external/jsoncpp/include -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/src/serializer/json
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/src/serializer/json/Serializer.cpp -o obj/external/CommonOptions/external/Serializer/src/serializer/json/Serializer.o  -I external/CommonOptions/external/Serializer/src/serializer -I external/CommonOptions/external/Serializer/src  -isystem external/CommonOptions/external/Serializer/external/jsoncpp/src -isystem external/CommonOptions/external/Serializer/external/jsoncpp/include -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/src/serializer/json
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/src/serializer/json/Deserializer.cpp -o obj/external/CommonOptions/external/Serializer/src/serializer/json/Deserializer.o  -I external/CommonOptions/external/Serializer/src/serializer -I external/CommonOptions/external/Serializer/src  -isystem external/CommonOptions/external/Serializer/external/jsoncpp/src -isystem external/CommonOptions/external/Serializer/external/jsoncpp/include -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/src/serializer/binary
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/src/serializer/binary/Serializer.cpp -o obj/external/CommonOptions/external/Serializer/src/serializer/binary/Serializer.o  -I external/CommonOptions/external/Serializer/src/serializer -I external/CommonOptions/external/Serializer/src  -isystem external/CommonOptions/external/Serializer/external/jsoncpp/src -isystem external/CommonOptions/external/Serializer/external/jsoncpp/include -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/src/serializer/binary
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/src/serializer/binary/Deserializer.cpp -o obj/external/CommonOptions/external/Serializer/src/serializer/binary/Deserializer.o  -I external/CommonOptions/external/Serializer/src/serializer -I external/CommonOptions/external/Serializer/src  -isystem external/CommonOptions/external/Serializer/external/jsoncpp/src -isystem external/CommonOptions/external/Serializer/external/jsoncpp/include -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/src/serializer/yaml
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/src/serializer/yaml/Serializer.cpp -o obj/external/CommonOptions/external/Serializer/src/serializer/yaml/Serializer.o  -I external/CommonOptions/external/Serializer/src/serializer -I external/CommonOptions/external/Serializer/src  -isystem external/CommonOptions/external/Serializer/external/jsoncpp/src -isystem external/CommonOptions/external/Serializer/external/jsoncpp/include -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/src/serializer/yaml
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/src/serializer/yaml/Deserializer.cpp -o obj/external/CommonOptions/external/Serializer/src/serializer/yaml/Deserializer.o  -I external/CommonOptions/external/Serializer/src/serializer -I external/CommonOptions/external/Serializer/src  -isystem external/CommonOptions/external/Serializer/external/jsoncpp/src -isystem external/CommonOptions/external/Serializer/external/jsoncpp/include -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/src/testSerializer
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/src/testSerializer/testHasSerializeFunction.cpp -o obj/external/CommonOptions/external/Serializer/src/testSerializer/testHasSerializeFunction.o  -I external/CommonOptions/external/Serializer/src/testSerializer -I external/CommonOptions/external/Serializer/src  -isystem external/ThreadPool/external/gtest/src -isystem external/ThreadPool/external/gtest/include -isystem external/CommonOptions/external/Serializer/src -isystem external/CommonOptions/external/Serializer/external/gtest/src -isystem external/CommonOptions/external/Serializer/external/gtest/include -isystem external/CommonOptions/external/Serializer/external/jsoncpp/src -isystem external/CommonOptions/external/Serializer/external/jsoncpp/include -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/src/testSerializer
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/src/testSerializer/testFundamentals.cpp -o obj/external/CommonOptions/external/Serializer/src/testSerializer/testFundamentals.o  -I external/CommonOptions/external/Serializer/src/testSerializer -I external/CommonOptions/external/Serializer/src  -isystem external/ThreadPool/external/gtest/src -isystem external/ThreadPool/external/gtest/include -isystem external/CommonOptions/external/Serializer/src -isystem external/CommonOptions/external/Serializer/external/gtest/src -isystem external/CommonOptions/external/Serializer/external/gtest/include -isystem external/CommonOptions/external/Serializer/external/jsoncpp/src -isystem external/CommonOptions/external/Serializer/external/jsoncpp/include -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/src/testSerializer
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/src/testSerializer/testPointers.cpp -o obj/external/CommonOptions/external/Serializer/src/testSerializer/testPointers.o  -I external/CommonOptions/external/Serializer/src/testSerializer -I external/CommonOptions/external/Serializer/src  -isystem external/ThreadPool/external/gtest/src -isystem external/ThreadPool/external/gtest/include -isystem external/CommonOptions/external/Serializer/src -isystem external/CommonOptions/external/Serializer/external/gtest/src -isystem external/CommonOptions/external/Serializer/external/gtest/include -isystem external/CommonOptions/external/Serializer/external/jsoncpp/src -isystem external/CommonOptions/external/Serializer/external/jsoncpp/include -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/jsoncpp/src/lib_json
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/jsoncpp/src/lib_json/json_reader.cpp -o obj/external/CommonOptions/external/Serializer/external/jsoncpp/src/lib_json/json_reader.o  -I external/CommonOptions/external/Serializer/external/jsoncpp/src/lib_json -I external/CommonOptions/external/Serializer/external/jsoncpp/include -I external/CommonOptions/external/Serializer/external/jsoncpp
mkdir -p obj/external/CommonOptions/external/Serializer/external/jsoncpp/src/lib_json
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/jsoncpp/src/lib_json/json_value.cpp -o obj/external/CommonOptions/external/Serializer/external/jsoncpp/src/lib_json/json_value.o  -I external/CommonOptions/external/Serializer/external/jsoncpp/src/lib_json -I external/CommonOptions/external/Serializer/external/jsoncpp/include -I external/CommonOptions/external/Serializer/external/jsoncpp
mkdir -p obj/external/CommonOptions/external/Serializer/external/jsoncpp/src/lib_json
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/jsoncpp/src/lib_json/json_writer.cpp -o obj/external/CommonOptions/external/Serializer/external/jsoncpp/src/lib_json/json_writer.o  -I external/CommonOptions/external/Serializer/external/jsoncpp/src/lib_json -I external/CommonOptions/external/Serializer/external/jsoncpp/include -I external/CommonOptions/external/Serializer/external/jsoncpp
mkdir -p obj/external/CommonOptions/external/Serializer/external/jsoncpp/src/testJsoncpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/jsoncpp/src/testJsoncpp/main.cpp -o obj/external/CommonOptions/external/Serializer/external/jsoncpp/src/testJsoncpp/main.o  -I external/CommonOptions/external/Serializer/external/jsoncpp/src/testJsoncpp -I external/CommonOptions/external/Serializer/external/jsoncpp/src  -isystem external/CommonOptions/external/Serializer/external/jsoncpp/src -isystem external/CommonOptions/external/Serializer/external/jsoncpp/include
mkdir -p obj/external/CommonOptions/external/Serializer/external/gtest/src/gtest/src
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/gtest/src/gtest/src/gtest_main.cpp -o obj/external/CommonOptions/external/Serializer/external/gtest/src/gtest/src/gtest_main.o  -I external/CommonOptions/external/Serializer/external/gtest/src/gtest -I external/CommonOptions/external/Serializer/external/gtest/include -I external/CommonOptions/external/Serializer/external/gtest
mkdir -p obj/external/CommonOptions/external/Serializer/external/gtest/src/gtest/src
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/gtest/src/gtest/src/gtest-all.cpp -o obj/external/CommonOptions/external/Serializer/external/gtest/src/gtest/src/gtest-all.o  -I external/CommonOptions/external/Serializer/external/gtest/src/gtest -I external/CommonOptions/external/Serializer/external/gtest/include -I external/CommonOptions/external/Serializer/external/gtest
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/binary.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/binary.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/stream.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/stream.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/simplekey.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/simplekey.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/scantag.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/scantag.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/emit.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/emit.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/emitterstate.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/emitterstate.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/regex_yaml.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/regex_yaml.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/tag.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/tag.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/scantoken.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/scantoken.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/memory.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/memory.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/null.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/null.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/parse.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/parse.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/emitter.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/emitter.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/exp.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/exp.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/parser.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/parser.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/emitterutils.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/emitterutils.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/directives.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/directives.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/exceptions.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/exceptions.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/singledocparser.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/singledocparser.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/node_data.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/node_data.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/nodebuilder.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/nodebuilder.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/emitfromevents.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/emitfromevents.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/convert.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/convert.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/scanner.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/scanner.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/scanscalar.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/scanscalar.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/ostream_wrapper.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/ostream_wrapper.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/nodeevents.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/nodeevents.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/contrib
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/contrib/graphbuilder.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/contrib/graphbuilder.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/contrib
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/contrib/graphbuilderadapter.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/contrib/graphbuilderadapter.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/node.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/node.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp -I external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/testsYaml
g++ -O0 -std=c++17 -fPIC -MD -g3 -ggdb -fdiagnostics-color=always -c external/CommonOptions/external/Serializer/external/yaml-cpp/src/testsYaml/main.cpp -o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/testsYaml/main.o  -I external/CommonOptions/external/Serializer/external/yaml-cpp/src/testsYaml -I external/CommonOptions/external/Serializer/external/yaml-cpp/src  -isystem external/CommonOptions/external/Serializer/external/yaml-cpp/src
mkdir -p lib
ar rcs lib/base64.a obj/src/base64/base64.o
mkdir -p lib
ar rcs lib/gtest.a obj/external/ThreadPool/external/gtest/src/gtest/src/gtest_main.o obj/external/ThreadPool/external/gtest/src/gtest/src/gtest-all.o
mkdir -p lib
ar rcs lib/process.a obj/external/CommonOptions/external/SelfTest/external/Process/src/process/InteractiveProcess.o obj/external/CommonOptions/external/SelfTest/external/Process/src/process/Process.o
mkdir -p lib
ar rcs lib/lib_json.a obj/external/CommonOptions/external/Serializer/external/jsoncpp/src/lib_json/json_reader.o obj/external/CommonOptions/external/Serializer/external/jsoncpp/src/lib_json/json_value.o obj/external/CommonOptions/external/Serializer/external/jsoncpp/src/lib_json/json_writer.o
mkdir -p lib
ar rcs lib/gtest.a obj/external/CommonOptions/external/Serializer/external/gtest/src/gtest/src/gtest_main.o obj/external/CommonOptions/external/Serializer/external/gtest/src/gtest/src/gtest-all.o
mkdir -p lib
ar rcs lib/yaml-cpp.a obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/binary.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/stream.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/simplekey.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/scantag.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/emit.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/emitterstate.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/regex_yaml.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/tag.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/scantoken.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/memory.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/null.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/parse.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/emitter.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/exp.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/parser.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/emitterutils.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/directives.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/exceptions.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/singledocparser.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/node_data.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/nodebuilder.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/emitfromevents.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/convert.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/scanner.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/scanscalar.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/ostream_wrapper.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/nodeevents.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/contrib/graphbuilder.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/contrib/graphbuilderadapter.o obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/yaml-cpp/node.o
mkdir -p bin
g++ -rdynamic -g3 -ggdb -fdiagnostics-color=always -o bin/testBase64 obj/src/testBase64/main.o lib/base64.a
mkdir -p lib
ar rcs lib/selfTest.a obj/external/CommonOptions/external/SelfTest/src/selfTest/selfTest.o
mkdir -p bin
g++ -rdynamic -g3 -ggdb -fdiagnostics-color=always -o bin/testProcess obj/external/CommonOptions/external/SelfTest/external/Process/src/testProcess/test.o lib/process.a -lpthread
mkdir -p bin
g++ -rdynamic -g3 -ggdb -fdiagnostics-color=always -o bin/testJsoncpp obj/external/CommonOptions/external/Serializer/external/jsoncpp/src/testJsoncpp/main.o lib/lib_json.a
mkdir -p bin
g++ -rdynamic -g3 -ggdb -fdiagnostics-color=always -o bin/testThreadPool obj/external/ThreadPool/src/testThreadPool/testThreadPool.o lib/gtest.a lib/gtest.a -lpthread
mkdir -p lib
ar rcs lib/serializer.a obj/external/CommonOptions/external/Serializer/src/serializer/json/Serializer.o obj/external/CommonOptions/external/Serializer/src/serializer/json/Deserializer.o obj/external/CommonOptions/external/Serializer/src/serializer/binary/Serializer.o obj/external/CommonOptions/external/Serializer/src/serializer/binary/Deserializer.o obj/external/CommonOptions/external/Serializer/src/serializer/yaml/Serializer.o obj/external/CommonOptions/external/Serializer/src/serializer/yaml/Deserializer.o
mkdir -p bin
g++ -rdynamic -g3 -ggdb -fdiagnostics-color=always -o bin/testsYaml obj/external/CommonOptions/external/Serializer/external/yaml-cpp/src/testsYaml/main.o lib/yaml-cpp.a
mkdir -p bin
g++ -rdynamic -g3 -ggdb -fdiagnostics-color=always -o bin/testSelfTest obj/external/CommonOptions/external/SelfTest/src/testSelfTest/test.o lib/selfTest.a lib/process.a -lpthread
mkdir -p bin
g++ -rdynamic -g3 -ggdb -fdiagnostics-color=always -o bin/busy obj/src/busy/busy.o obj/src/busy/Project.o obj/src/busy/cache.o obj/src/busy/File.o obj/src/busy/toolchains.o obj/src/busy/FileCache.o obj/src/busy/utils/utils.o obj/src/busy/Package.o obj/src/busy/CompilePipe.o lib/base64.a lib/process.a lib/yaml-cpp.a lib/yaml-cpp.a -lstdc++fs -lpthread
mkdir -p bin
g++ -rdynamic -g3 -ggdb -fdiagnostics-color=always -o bin/exampleSerializer obj/external/CommonOptions/external/Serializer/src/exampleSerializer/testFundamentals.o lib/serializer.a lib/lib_json.a lib/yaml-cpp.a
mkdir -p bin
g++ -rdynamic -g3 -ggdb -fdiagnostics-color=always -o bin/exampleSerializerBinary obj/external/CommonOptions/external/Serializer/src/exampleSerializerBinary/testFundamentals.o lib/serializer.a lib/lib_json.a lib/yaml-cpp.a
mkdir -p bin
g++ -rdynamic -g3 -ggdb -fdiagnostics-color=always -o bin/testSerializer obj/external/CommonOptions/external/Serializer/src/testSerializer/testHasSerializeFunction.o obj/external/CommonOptions/external/Serializer/src/testSerializer/testFundamentals.o obj/external/CommonOptions/external/Serializer/src/testSerializer/testPointers.o lib/gtest.a lib/serializer.a lib/gtest.a lib/lib_json.a lib/yaml-cpp.a -lpthread
