#include "commands.h"
#include <iostream>

using namespace aBuild;

namespace commands {


void toolchains() {
	Workspace ws(".");
	auto toolchains    = getAllToolchains(ws);
	auto installations = getAllInstallations(ws);

	int longestString = 0;
	for (auto const& e : toolchains) {
		longestString = std::max(longestString, int(e.second.getName().length()));
	}

	for (auto const& e : toolchains) {
		auto const& tc = e.second;
		std::cout << tc.getName();
		for (int i (tc.getName().length()); i < longestString; ++i) {
			std::cout << " ";
		}
		bool installed = tc.isInstalled(installations);
		if (installed) {
			std::cout << " (installed";
		} else {
			std::cout << " (not installed";
		}
		if (tc.isAutoGenerated()) {
			std::cout << "/auto generated";
		}
		std::cout << ")" << std::endl;
	}
}

}
