#include "Toolchain.h"

#include "Installation.h"

#include <iostream>

namespace busy {

Toolchain::Toolchain(busyConfig::Toolchain const& _toolchain) {
	autoGenerated = false;
	name          = _toolchain.name;
	cCompiler     = _toolchain.cCompiler;
	cppCompiler   = _toolchain.cppCompiler;
	archivist     = _toolchain.archivist;
	installations = _toolchain.installations;

}


bool Toolchain::isInstalled(std::map<std::string, Installation> const& installations) const {
	for (auto const& i : getInstallations()) {
		if (installations.find(i) == installations.end()) {
			return false;
		}
		if (not installations.at(i).isInstalled()) {
			return false;
		}
	}
	return true;
}
void Toolchain::install(std::map<std::string, Installation> const& installations) const {
	for (auto const& i : getInstallations()) {
		if (installations.find(i) == installations.end()) {
			std::cout << "unclear how to install " << i << std::endl;
			return;
		}
		if (not installations.at(i).isInstalled()) {
			installations.at(i).install();
		}

	}
}


}

